"""ListingWriterAgent - 商品説明・メタデータ自動生成エージェント

カタログ内の品質通過アセットを分析し、販売プラットフォーム向けの
商品説明・タグ・メタデータを生成する。
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from ..agent import Asset, BaseAgent, Context

logger = logging.getLogger(__name__)

PLATFORM_TEMPLATES = {
    "booth": {
        "max_title": 60,
        "max_description": 3000,
        "format": "markdown",
    },
    "gumroad": {
        "max_title": 100,
        "max_description": 5000,
        "format": "html",
    },
}

LISTING_TEMPLATES = {
    "audio_pack": {
        "ja": {
            "title": "{theme}足音パック - {count}種類のAI生成サウンド",
            "description": (
                "## {theme}足音パック\n\n"
                "AI（Stable Audio Open）で生成した高品質足音エフェクト集。\n\n"
                "### 収録内容\n"
                "- サーフェス: {surfaces}\n"
                "- 各サーフェス{per_surface}バリエーション\n"
                "- 合計{count}ファイル（WAV形式）\n\n"
                "### 特徴\n"
                "- VRChat / Unity対応\n"
                "- ロイヤリティフリー\n"
                "- 商用利用OK\n"
            ),
            "tags": ["VRChat", "足音", "SE", "効果音", "Unity", "{theme}"],
        },
        "en": {
            "title": "{theme} Footstep Pack - {count} AI-Generated Sounds",
            "description": (
                "## {theme} Footstep Pack\n\n"
                "High-quality footstep sound effects generated by AI (Stable Audio Open).\n\n"
                "### Contents\n"
                "- Surfaces: {surfaces}\n"
                "- {per_surface} variations per surface\n"
                "- {count} files total (WAV format)\n\n"
                "### Features\n"
                "- VRChat / Unity compatible\n"
                "- Royalty-free\n"
                "- Commercial use OK\n"
            ),
            "tags": ["VRChat", "footstep", "SFX", "sound effect", "Unity", "{theme}"],
        },
    },
    "image_variants": {
        "ja": {
            "title": "{style}テクスチャパック - {count}枚の高解像度素材",
            "description": (
                "## {style}テクスチャパック\n\n"
                "AI（Real-ESRGAN）でアップスケールした高解像度テクスチャ集。\n\n"
                "### 収録内容\n"
                "- {count}枚のテクスチャ\n"
                "- {scale}倍アップスケール済み\n\n"
                "### 特徴\n"
                "- VRChatアバター対応\n"
                "- 高解像度（最大4K）\n"
            ),
            "tags": ["VRChat", "テクスチャ", "アバター", "高画質", "{style}"],
        },
        "en": {
            "title": "{style} Texture Pack - {count} High-Resolution Assets",
            "description": (
                "## {style} Texture Pack\n\n"
                "High-resolution textures upscaled by AI (Real-ESRGAN).\n\n"
                "### Contents\n"
                "- {count} textures\n"
                "- {scale}x upscaled\n\n"
                "### Features\n"
                "- VRChat avatar compatible\n"
                "- High resolution (up to 4K)\n"
            ),
            "tags": ["VRChat", "texture", "avatar", "high-quality", "{style}"],
        },
    },
}

THEME_NAMES_JA = {
    "horror": "ホラー",
    "scifi": "SF",
    "fantasy": "ファンタジー",
    "nature": "ネイチャー",
    "urban": "アーバン",
}

STYLE_NAMES_JA = {
    "anime": "アニメ調",
    "realistic": "リアル調",
}


class ListingWriterAgent(BaseAgent):
    name = "listing_writer"
    description = "商品説明・メタデータ自動生成"
    interval_seconds = 7200
    requires = []
    monetization = "indirect"

    def __init__(self, params: dict[str, Any] | None = None):
        super().__init__(params)
        self.languages = self.params.get("languages", ["ja", "en"])
        self.platforms = self.params.get("platforms", ["booth", "gumroad"])

    def _analyze_audio_packs(self, catalog: Any) -> list[dict[str, Any]]:
        """カタログから音源パックの構成を分析する。"""
        audio_assets = catalog.query(agent="audio_pack", status="quality_passed")
        packs: dict[str, dict[str, int]] = {}

        for asset in audio_assets:
            theme = asset.metadata.get("theme", "unknown")
            surface = asset.metadata.get("surface", "unknown")
            if theme not in packs:
                packs[theme] = {}
            packs[theme][surface] = packs[theme].get(surface, 0) + 1

        result = []
        for theme, surfaces in packs.items():
            total = sum(surfaces.values())
            if total >= 5:  # 最低5ファイルでパック化
                result.append({
                    "type": "audio_pack",
                    "theme": theme,
                    "surfaces": surfaces,
                    "total_count": total,
                })
        return result

    def _analyze_image_packs(self, catalog: Any) -> list[dict[str, Any]]:
        """カタログからテクスチャパックの構成を分析する。"""
        image_assets = catalog.query(agent="image_variants", status="quality_passed")
        packs: dict[str, list[Any]] = {}

        for asset in image_assets:
            style = asset.metadata.get("style", "unknown")
            if style not in packs:
                packs[style] = []
            packs[style].append(asset)

        result = []
        for style, assets in packs.items():
            if len(assets) >= 3:  # 最低3枚でパック化
                result.append({
                    "type": "image_variants",
                    "style": style,
                    "count": len(assets),
                    "scale": assets[0].metadata.get("scale", 4) if assets else 4,
                })
        return result

    def _generate_listing(
        self, pack: dict[str, Any], lang: str, platform: str
    ) -> dict[str, Any]:
        """パック情報から商品説明を生成する。"""
        pack_type = pack["type"]
        templates = LISTING_TEMPLATES.get(pack_type, {}).get(lang, {})
        if not templates:
            return {}

        if pack_type == "audio_pack":
            theme = pack["theme"]
            theme_display = THEME_NAMES_JA.get(theme, theme) if lang == "ja" else theme.title()
            surfaces = ", ".join(pack["surfaces"].keys())
            per_surface = max(pack["surfaces"].values()) if pack["surfaces"] else 0

            title = templates["title"].format(
                theme=theme_display, count=pack["total_count"]
            )
            description = templates["description"].format(
                theme=theme_display,
                surfaces=surfaces,
                per_surface=per_surface,
                count=pack["total_count"],
            )
            tags = [t.format(theme=theme_display) for t in templates["tags"]]

        elif pack_type == "image_variants":
            style = pack["style"]
            style_display = STYLE_NAMES_JA.get(style, style) if lang == "ja" else style.title()

            title = templates["title"].format(
                style=style_display, count=pack["count"]
            )
            description = templates["description"].format(
                style=style_display,
                count=pack["count"],
                scale=pack.get("scale", 4),
            )
            tags = [t.format(style=style_display) for t in templates["tags"]]
        else:
            return {}

        platform_config = PLATFORM_TEMPLATES.get(platform, {})
        max_title = platform_config.get("max_title", 100)
        if len(title) > max_title:
            title = title[:max_title - 3] + "..."

        return {
            "title": title,
            "description": description,
            "tags": tags,
            "platform": platform,
            "language": lang,
        }

    def run(self, ctx: Context) -> list[Asset]:
        audio_packs = self._analyze_audio_packs(ctx.catalog)
        image_packs = self._analyze_image_packs(ctx.catalog)
        all_packs = audio_packs + image_packs

        if not all_packs:
            logger.info("[listing_writer] パック化可能なアセットなし")
            return []

        assets: list[Asset] = []

        for pack in all_packs:
            for lang in self.languages:
                for platform in self.platforms:
                    pack_type = pack["type"]
                    identifier = pack.get("theme", pack.get("style", "unknown"))

                    # 既に生成済みかチェック
                    asset_id = f"listing_{pack_type}_{identifier}_{lang}_{platform}"
                    existing = ctx.catalog.count(
                        agent=self.name,
                        pack_type=pack_type,
                        identifier=identifier,
                        language=lang,
                        platform=platform,
                    )
                    if existing > 0:
                        continue

                    listing = self._generate_listing(pack, lang, platform)
                    if not listing:
                        continue

                    # ファイルに保存
                    output_path = (
                        ctx.output_dir
                        / "listings"
                        / platform
                        / lang
                        / f"{pack_type}_{identifier}.json"
                    )
                    output_path.parent.mkdir(parents=True, exist_ok=True)
                    with open(output_path, "w", encoding="utf-8") as f:
                        json.dump(listing, f, ensure_ascii=False, indent=2)

                    asset = Asset(
                        id=asset_id,
                        agent=self.name,
                        type="text/json",
                        path=str(output_path),
                        monetization="indirect",
                        estimated_value_yen=0.0,  # 間接価値のため0
                        metadata={
                            "pack_type": pack_type,
                            "identifier": identifier,
                            "language": lang,
                            "platform": platform,
                            "title": listing["title"],
                        },
                    )
                    assets.append(asset)

        return assets

    def estimate_value(self, catalog: Any) -> float:
        # listing自体の直接価値は低いが、販売を可能にする点で重要
        audio_packs = self._analyze_audio_packs(catalog)
        image_packs = self._analyze_image_packs(catalog)
        unlisted = len(audio_packs) + len(image_packs)
        return unlisted * 100.0  # パックあたり¥100の間接価値
