"""PackagerAgent - BOOTH出品パッケージング自動化エージェント

カタログ内の品質通過アセットを集約し、BOOTH出品可能な状態にパッケージングする。

生成物:
  output/packages/{product_id}/
  ├── {product_id}.zip        # 配布ファイル
  ├── thumbnail.png           # BOOTHサムネイル（620x620）
  ├── listing_ja.md           # 日本語商品説明
  ├── listing_en.md           # 英語商品説明
  └── cross_references.json   # 関連商品リスト
"""

from __future__ import annotations

import json
import logging
import shutil
import zipfile
from pathlib import Path
from typing import Any

from ..agent import Asset, BaseAgent, Context

logger = logging.getLogger(__name__)

# 商品定義テンプレート
PRODUCT_TEMPLATES = {
    "frame_pack": {
        "price_yen": 100,
        "category": "chatbox_decorator",
        "icon": "✨",
        "listing_ja": (
            "## {name_ja}\n\n"
            "VRChat Chatbox デコレーター用の拡張フレームパックです。\n\n"
            "### 収録内容\n"
            "- {frame_count}種類のフレーム\n"
            "- テーマ: {name_ja}\n\n"
            "### 使い方\n"
            "1. frames.json をダウンロード\n"
            "2. Chatbox デコレーターの FRAMES 辞書に追加\n"
            "3. VRChat で使用！\n\n"
            "### 動作環境\n"
            "- Python 3.10+\n"
            "- VRChat (PC版)\n"
        ),
        "listing_en": (
            "## {name_en}\n\n"
            "Extension frame pack for VRChat Chatbox Decorator.\n\n"
            "### Contents\n"
            "- {frame_count} frame styles\n"
            "- Theme: {name_en}\n\n"
            "### How to Use\n"
            "1. Download frames.json\n"
            "2. Add entries to Chatbox Decorator's FRAMES dictionary\n"
            "3. Use in VRChat!\n\n"
            "### Requirements\n"
            "- Python 3.10+\n"
            "- VRChat (PC)\n"
        ),
        "tags_ja": ["VRChat", "Chatbox", "デコレーション", "OSC"],
        "tags_en": ["VRChat", "Chatbox", "Decoration", "OSC"],
    },
    "fortune_pack": {
        "price_yen": 100,
        "category": "omikuji_bot",
        "icon": "⛩️",
        "listing_ja": (
            "## {name_ja}\n\n"
            "VRChat おみくじBot用の拡張占いデータパックです。\n\n"
            "### 収録内容\n"
            "- {fortune_count}種類の運勢\n"
            "- {item_count}種類のラッキーアイテム\n"
            "- テーマ別アドバイス\n\n"
            "### 使い方\n"
            "1. fortune_data.json をダウンロード\n"
            "2. おみくじBotのデータディレクトリに配置\n"
            "3. テーマを指定して起動！\n\n"
            "### 動作環境\n"
            "- Python 3.10+\n"
            "- VRChat (PC版)\n"
        ),
        "listing_en": (
            "## {name_en}\n\n"
            "Extension fortune data pack for VRChat Omikuji Bot.\n\n"
            "### Contents\n"
            "- {fortune_count} fortune types\n"
            "- {item_count} lucky items\n"
            "- Theme-specific advice\n\n"
            "### How to Use\n"
            "1. Download fortune_data.json\n"
            "2. Place in Omikuji Bot data directory\n"
            "3. Start with theme option!\n\n"
            "### Requirements\n"
            "- Python 3.10+\n"
            "- VRChat (PC)\n"
        ),
        "tags_ja": ["VRChat", "おみくじ", "占い", "OSC"],
        "tags_en": ["VRChat", "Omikuji", "Fortune", "OSC"],
    },
    "audio_pack": {
        "price_yen": 300,
        "category": "footstep",
        "icon": "👣",
        "listing_ja": (
            "## {name_ja}\n\n"
            "AI（Stable Audio Open）で生成した高品質足音エフェクト集。\n\n"
            "### 収録内容\n"
            "- サーフェス: {surfaces}\n"
            "- 合計{total_count}ファイル（WAV形式）\n\n"
            "### 特徴\n"
            "- VRChat / Unity対応\n"
            "- ロイヤリティフリー\n"
            "- 商用利用OK\n"
        ),
        "listing_en": (
            "## {name_en}\n\n"
            "High-quality footstep SFX generated by AI (Stable Audio Open).\n\n"
            "### Contents\n"
            "- Surfaces: {surfaces}\n"
            "- {total_count} files total (WAV format)\n\n"
            "### Features\n"
            "- VRChat / Unity compatible\n"
            "- Royalty-free\n"
            "- Commercial use OK\n"
        ),
        "tags_ja": ["VRChat", "足音", "SE", "効果音", "Unity"],
        "tags_en": ["VRChat", "footstep", "SFX", "sound effect", "Unity"],
    },
}

# サムネイルのカラーテーママッピング
THEME_COLORS = {
    "seasonal_spring": "pink",
    "seasonal_summer": "blue",
    "seasonal_autumn": "orange",
    "seasonal_winter": "blue",
    "horror": "dark",
    "rpg": "purple",
    "kaomoji": "pink",
    "retro_game": "red",
    "halloween": "orange",
    "valentine": "pink",
    "christmas": "red",
    "newyear": "gold",
    "gaming": "purple",
    "scifi": "blue",
    "fantasy": "green",
    "nature": "green",
    "urban": "dark",
}


class PackagerAgent(BaseAgent):
    name = "packager"
    description = "BOOTH出品パッケージング自動化"
    interval_seconds = 3600
    requires = []
    monetization = "indirect"

    def __init__(self, params: dict[str, Any] | None = None):
        super().__init__(params)
        self.max_per_cycle = self.params.get("max_per_cycle", 5)

    def _find_unpackaged(self, catalog: Any) -> list[Asset]:
        """品質通過済みだが未パッケージのアセットを見つける。"""
        passed = catalog.query(status="quality_passed")
        packaged_ids = {
            a.metadata.get("source_asset_id")
            for a in catalog.query(agent=self.name)
        }
        return [a for a in passed if a.id not in packaged_ids]

    def _create_package(
        self, asset: Asset, output_dir: Path, catalog: Any
    ) -> Asset | None:
        """1つのアセットからBOOTH出品パッケージを生成する。"""
        product_type = asset.metadata.get("product_type", asset.agent)
        template = PRODUCT_TEMPLATES.get(product_type)
        if not template:
            return None

        theme = asset.metadata.get("theme", "default")
        product_id = f"{product_type}_{theme}"
        pkg_dir = output_dir / "packages" / product_id
        pkg_dir.mkdir(parents=True, exist_ok=True)

        # 1. アセットファイルをコピー
        source_path = Path(asset.path)
        if source_path.exists():
            # アセットのディレクトリ全体をコピー
            source_dir = source_path.parent
            content_dir = pkg_dir / "content"
            if content_dir.exists():
                shutil.rmtree(content_dir)
            shutil.copytree(source_dir, content_dir)
        else:
            logger.warning(f"ソースファイルなし: {source_path}")
            return None

        # 2. 商品説明を生成
        format_vars = {
            "name_ja": asset.metadata.get("name_ja", theme),
            "name_en": asset.metadata.get("name_en", theme),
            "theme": theme,
            **asset.metadata,
        }
        # テンプレート内の未定義変数を安全に処理
        listing_ja = _safe_format(template["listing_ja"], format_vars)
        listing_en = _safe_format(template["listing_en"], format_vars)

        (pkg_dir / "listing_ja.md").write_text(listing_ja, encoding="utf-8")
        (pkg_dir / "listing_en.md").write_text(listing_en, encoding="utf-8")

        # 3. クロスリファレンス生成
        cross_refs = self._generate_cross_references(
            product_type, theme, catalog
        )
        with open(pkg_dir / "cross_references.json", "w", encoding="utf-8") as f:
            json.dump(cross_refs, f, ensure_ascii=False, indent=2)

        # 4. サムネイル生成（Pillow利用可能な場合）
        thumbnail_path = pkg_dir / "thumbnail.png"
        self._generate_thumbnail(
            title=asset.metadata.get("name_ja", theme),
            theme_color=THEME_COLORS.get(theme, "purple"),
            icon=template.get("icon", "🎮"),
            output_path=thumbnail_path,
        )

        # 5. ZIP生成
        zip_path = pkg_dir / f"{product_id}.zip"
        self._create_zip(pkg_dir, zip_path, content_dir)

        # 6. メタデータ
        meta = {
            "product_id": product_id,
            "product_type": product_type,
            "theme": theme,
            "price_yen": template["price_yen"],
            "tags_ja": template["tags_ja"],
            "tags_en": template["tags_en"],
            "cross_references": cross_refs,
            "has_thumbnail": thumbnail_path.exists(),
            "source_asset_id": asset.id,
        }
        with open(pkg_dir / "metadata.json", "w", encoding="utf-8") as f:
            json.dump(meta, f, ensure_ascii=False, indent=2)

        return Asset(
            id=f"package_{product_id}",
            agent=self.name,
            type="application/zip",
            path=str(zip_path),
            monetization="direct_sale",
            estimated_value_yen=float(template["price_yen"]),
            metadata={
                "product_id": product_id,
                "product_type": product_type,
                "theme": theme,
                "price_yen": template["price_yen"],
                "source_asset_id": asset.id,
                "cross_ref_count": len(cross_refs),
            },
        )

    def _generate_cross_references(
        self, product_type: str, theme: str, catalog: Any
    ) -> list[dict[str, str]]:
        """同カテゴリの関連商品リストを生成する。"""
        refs = []
        # 同タイプの他テーマ
        same_type = catalog.query(agent="catalog_expander")
        for asset in same_type:
            if (
                asset.metadata.get("product_type") == product_type
                and asset.metadata.get("theme") != theme
            ):
                refs.append({
                    "product_id": f"{product_type}_{asset.metadata.get('theme', '')}",
                    "name_ja": asset.metadata.get("name_ja", ""),
                    "name_en": asset.metadata.get("name_en", ""),
                    "type": "same_category",
                })

        # 別タイプだが関連性のあるもの（同テーマ名を含む）
        for asset in same_type:
            if (
                asset.metadata.get("product_type") != product_type
                and asset.metadata.get("theme") == theme
            ):
                other_type = asset.metadata.get("product_type", "")
                refs.append({
                    "product_id": f"{other_type}_{theme}",
                    "name_ja": asset.metadata.get("name_ja", ""),
                    "name_en": asset.metadata.get("name_en", ""),
                    "type": "same_theme",
                })

        return refs

    def _generate_thumbnail(
        self,
        title: str,
        theme_color: str,
        icon: str,
        output_path: Path,
    ) -> bool:
        """サムネイル画像を生成する（Pillow使用）。"""
        try:
            from PIL import Image, ImageDraw, ImageFont
        except ImportError:
            logger.debug("Pillow未インストール、サムネイル生成をスキップ")
            return False

        width, height = 620, 620

        # カラーテーマ
        colors = {
            "purple": ("#6C5CE7", "#341f97"),
            "blue": ("#0984e3", "#0652DD"),
            "green": ("#00b894", "#006266"),
            "red": ("#e17055", "#c0392b"),
            "pink": ("#e84393", "#B53471"),
            "orange": ("#e17055", "#d35400"),
            "dark": ("#2d3436", "#0d0d0d"),
            "gold": ("#f9ca24", "#f0932b"),
        }
        bg1, bg2 = colors.get(theme_color, colors["purple"])

        # 単色背景（グラデーション簡略化）
        img = Image.new("RGB", (width, height), bg1)
        draw = ImageDraw.Draw(img)

        # 下半分をbg2で塗る（擬似グラデーション）
        draw.rectangle(
            [(0, height // 2), (width, height)], fill=bg2
        )

        # テキスト描画（デフォルトフォント）
        try:
            font_large = ImageFont.truetype(
                "/usr/share/fonts/opentype/ipafont-gothic/ipag.ttf", 36
            )
            font_small = ImageFont.truetype(
                "/usr/share/fonts/opentype/ipafont-gothic/ipag.ttf", 18
            )
        except (OSError, IOError):
            font_large = ImageFont.load_default()
            font_small = font_large

        # タイトル
        bbox = draw.textbbox((0, 0), title, font=font_large)
        tw = bbox[2] - bbox[0]
        draw.text(
            ((width - tw) // 2, height // 2 - 30),
            title,
            font=font_large,
            fill="#FFFFFF",
        )

        # ブランド
        brand = "VRC Tools"
        bbox = draw.textbbox((0, 0), brand, font=font_small)
        bw = bbox[2] - bbox[0]
        draw.text(
            ((width - bw) // 2, height - 60),
            brand,
            font=font_small,
            fill="#CCCCCC",
        )

        img.save(str(output_path), "PNG")
        return True

    def _create_zip(
        self, pkg_dir: Path, zip_path: Path, content_dir: Path
    ) -> None:
        """配布用ZIPを作成する。"""
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            # content/ 内のファイルを追加
            if content_dir.exists():
                for file in content_dir.rglob("*"):
                    if file.is_file():
                        arcname = file.relative_to(content_dir)
                        zf.write(file, arcname)
            # READMEとlistingを追加
            for md_file in pkg_dir.glob("*.md"):
                zf.write(md_file, md_file.name)

    def run(self, ctx: Context) -> list[Asset]:
        unpackaged = self._find_unpackaged(ctx.catalog)
        if not unpackaged:
            logger.info("[packager] パッケージ対象のアセットなし")
            return []

        assets: list[Asset] = []
        for asset in unpackaged[: self.max_per_cycle]:
            pkg = self._create_package(asset, ctx.output_dir, ctx.catalog)
            if pkg:
                assets.append(pkg)
                logger.info(
                    f"[packager] パッケージ生成: {pkg.metadata.get('product_id')}"
                )

        return assets

    def estimate_value(self, catalog: Any) -> float:
        unpackaged = self._find_unpackaged(catalog)
        # 未パッケージの数 × 平均価格でスコア
        return len(unpackaged) * 150.0


def _safe_format(template: str, vars: dict[str, Any]) -> str:
    """テンプレートの未定義変数を空文字で置換する安全なformat。"""
    import re

    def replacer(match: re.Match) -> str:
        key = match.group(1)
        val = vars.get(key, "")
        return str(val)

    return re.sub(r"\{(\w+)\}", replacer, template)
